CREATE TABLE MEMBER(
	ID VARCHAR2(30) PRIMARY KEY,
	PWD VARCHAR2(30)	NOT NULL,
	NAME VARCHAR2(30)	NOT NULL,
	EMAIL VARCHAR2(30) UNIQUE,
	AUTH NUMBER(1)
);

SELECT * FROM MEMBER;


CREATE TABLE ACCOUNTBOOK(
	SEQ NUMBER(8),			
	ID VARCHAR2(30),		-- 외래키
	IO_KIND VARCHAR2(1),	-- 수입/지출
	AMOUNT NUMBER(9),		-- 금액
	CONTENT VARCHAR2(200),	-- 내용
	WDATE DATE				-- 입력일
);

-- SEQUENCE
CREATE SEQUENCE SEQ_BOOK
START WITH 1
INCREMENT BY 1;

-- 외래키(ID)
ALTER TABLE ACCOUNTBOOK
ADD CONSTRAINT FK_BOOK FOREIGN KEY(ID)
REFERENCES MEMBER(ID);


SELECT * FROM ACCOUNTBOOK;
